# Generated by Django 4.0.6 on 2022-07-28 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='myProjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('image', models.ImageField(default='', upload_to='images/')),
                ('desc', models.CharField(default='no description provided', max_length=322)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('image', models.ImageField(upload_to='profile/')),
                ('bio', models.CharField(max_length=3222)),
                ('phone', models.CharField(max_length=3222)),
                ('email', models.CharField(max_length=3222)),
                ('address', models.CharField(max_length=3222)),
            ],
        ),
    ]
