# Generated by Django 4.0.6 on 2022-07-28 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coderhouse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myprojects',
            name='url',
            field=models.CharField(default='#', max_length=1222),
        ),
        migrations.AddField(
            model_name='profile',
            name='facebook',
            field=models.CharField(default='#', max_length=122),
        ),
        migrations.AddField(
            model_name='profile',
            name='github',
            field=models.CharField(default='#', max_length=12223),
        ),
        migrations.AddField(
            model_name='profile',
            name='instagram',
            field=models.CharField(default='#', max_length=12223),
        ),
        migrations.AddField(
            model_name='profile',
            name='linkdin',
            field=models.CharField(default='#', max_length=12223),
        ),
        migrations.AlterField(
            model_name='myprojects',
            name='desc',
            field=models.CharField(default='', max_length=322),
        ),
    ]
