# Generated by Django 4.0.6 on 2022-11-05 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coderhouse', '0002_myprojects_url_profile_facebook_profile_github_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=122, null=True)),
                ('eno', models.CharField(blank=True, default='', max_length=122, null=True)),
                ('phone', models.IntegerField(blank=True, null=True)),
                ('proj_title', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('technology', models.CharField(blank=True, default='', max_length=122, null=True)),
                ('frontend_tech', models.TextField(blank=True, default='', null=True)),
                ('backend_tech', models.TextField(blank=True, default='', null=True)),
                ('proj_desc', models.TextField(blank=True, default='', null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
